<?php

namespace Database\Seeders;

use App\Models\PageSeo;
use Illuminate\Database\Seeder;

class PageSeoSeeder extends Seeder
{
    public function run(): void
    {
        $cdn = rtrim(config('app.asset_url', 'https://assets.graveyardjokes.com'), '/');
        $base = 'https://graveyardjokes.com';

        $pages = [
            [
                'page_key' => 'home',
                'page_label' => 'Home',
                'page_url' => '/',
                'title' => 'Graveyard Jokes Studios | Custom Websites for Entrepreneurs, Creatives, and Independent Brands',
                'meta_description' => 'GraveyardJokes is a web design and development company creating fast, modern websites that help businesses generate leads and grow online.',
                'canonical_url' => $base . '/',
                'robots' => 'index,follow',
                'og_title' => 'Graveyard Jokes Studios | Custom Websites for Entrepreneurs, Creatives, and Independent Brands',
                'og_description' => 'GraveyardJokes is a web design and development company creating fast, modern websites that help businesses generate leads and grow online.',
                'og_image' => $cdn . '/images/AdobeStock_327183052.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Graveyard Jokes Studios | Custom Websites for Entrepreneurs, Creatives, and Independent Brands',
                'twitter_description' => 'GraveyardJokes is a web design and development company creating fast, modern websites that help businesses generate leads and grow online.',
                'twitter_image' => $cdn . '/images/AdobeStock_327183052.webp',
                'schema_json' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Organization',
                    'name' => 'GraveYard Jokes Studios Inc.',
                    'url' => $base,
                    'logo' => $cdn . '/images/logo.webp',
                    'sameAs' => [
                        'https://www.linkedin.com/in/joshua-ackerly',
                        'https://github.com/joshua-ackerly',
                    ],
                ],
                'sitemap_priority' => 1.00,
                'sitemap_change_freq' => 'weekly',
            ],
            [
                'page_key' => 'about',
                'page_label' => 'About',
                'page_url' => '/about',
                'title' => 'About Joshua Ackerly | Graveyard Jokes Studios',
                'meta_description' => 'Meet GraveyardJokes, a web design and development team focused on clean UX, reliable code, and websites built to convert visitors into customers.',
                'canonical_url' => $base . '/about',
                'robots' => 'index,follow',
                'og_title' => 'About Joshua Ackerly | Graveyard Jokes Studios',
                'og_description' => 'Meet GraveyardJokes, a web design and development team focused on clean UX, reliable code, and websites built to convert visitors into customers.',
                'og_image' => $cdn . '/images/aboutBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'About Joshua Ackerly | Graveyard Jokes Studios',
                'twitter_description' => 'Meet GraveyardJokes, a web design and development team focused on clean UX, reliable code, and websites built to convert visitors into customers.',
                'twitter_image' => $cdn . '/images/aboutBanner.webp',
                'schema_json' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Person',
                    'name' => 'Joshua Ackerly',
                    'url' => $base,
                    'sameAs' => [
                        'https://www.linkedin.com/in/joshua-ackerly',
                        'https://github.com/JoshuaAckerly',
                    ],
                    'jobTitle' => 'Full-Stack Web Developer',
                    'worksFor' => [
                        '@type' => 'Organization',
                        'name' => 'GraveYard Jokes Studios Inc.',
                    ],
                ],
                'sitemap_priority' => 0.70,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'contact',
                'page_label' => 'Contact',
                'page_url' => '/contact',
                'title' => 'Contact | Graveyard Jokes Studios',
                'meta_description' => 'Contact Graveyard Jokes Studios for custom websites. Get in touch to discuss your project.',
                'canonical_url' => $base . '/contact',
                'robots' => 'index,follow',
                'og_title' => 'Contact | Graveyard Jokes Studios',
                'og_description' => 'Contact Graveyard Jokes Studios for custom websites. Get in touch to discuss your project.',
                'og_image' => $cdn . '/images/ContactBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Contact | Graveyard Jokes Studios',
                'twitter_description' => 'Contact Graveyard Jokes Studios for custom websites. Get in touch to discuss your project.',
                'twitter_image' => $cdn . '/images/ContactBanner.webp',
                'schema_json' => null,
                'sitemap_priority' => 0.60,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'portfolio',
                'page_label' => 'Portfolio',
                'page_url' => '/portfolio',
                'title' => 'Portfolio | Graveyard Jokes Studios',
                'meta_description' => 'Explore the portfolio of Graveyard Jokes Studios, showcasing custom websites for entrepreneurs, creatives, and independent brands.',
                'canonical_url' => $base . '/portfolio',
                'robots' => 'index,follow',
                'og_title' => 'Portfolio | Graveyard Jokes Studios',
                'og_description' => 'Explore the portfolio of Graveyard Jokes Studios, showcasing custom websites for entrepreneurs, creatives, and independent brands.',
                'og_image' => $cdn . '/images/PortfolioBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Portfolio | Graveyard Jokes Studios',
                'twitter_description' => 'Explore the portfolio of Graveyard Jokes Studios, showcasing custom websites for entrepreneurs, creatives, and independent brands.',
                'twitter_image' => $cdn . '/images/PortfolioBanner.webp',
                'schema_json' => null,
                'sitemap_priority' => 0.80,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'studio',
                'page_label' => 'Studio',
                'page_url' => '/studio',
                'title' => 'Studio | Graveyard Jokes Studios',
                'meta_description' => 'Graveyard Jokes Studios — a creative web development studio building custom platforms for entrepreneurs, creatives, and independent brands.',
                'canonical_url' => $base . '/studio',
                'robots' => 'index,follow',
                'og_title' => 'Studio | Graveyard Jokes Studios',
                'og_description' => 'Graveyard Jokes Studios — a creative web development studio building custom platforms for entrepreneurs, creatives, and independent brands.',
                'og_image' => $cdn . '/images/aboutBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Studio | Graveyard Jokes Studios',
                'twitter_description' => 'Graveyard Jokes Studios — a creative web development studio building custom platforms for entrepreneurs, creatives, and independent brands.',
                'twitter_image' => $cdn . '/images/aboutBanner.webp',
                'schema_json' => null,
                'sitemap_priority' => 0.50,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'services',
                'page_label' => 'Services & Pricing',
                'page_url' => '/services',
                'title' => 'Services & Pricing | Graveyard Jokes Studios',
                'meta_description' => 'Graveyard Jokes Studios offers affordable web development, web design, and social media management for small businesses and independent brands.',
                'canonical_url' => $base . '/services',
                'robots' => 'index,follow',
                'og_title' => 'Services & Pricing | Graveyard Jokes Studios',
                'og_description' => 'Graveyard Jokes Studios offers affordable web development, web design, and social media management for small businesses and independent brands.',
                'og_image' => $cdn . '/images/aboutBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Services & Pricing | Graveyard Jokes Studios',
                'twitter_description' => 'Graveyard Jokes Studios offers affordable web development, web design, and social media management for small businesses and independent brands.',
                'twitter_image' => $cdn . '/images/aboutBanner.webp',
                'schema_json' => null,
                'sitemap_priority' => 0.90,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'services.starter',
                'page_label' => 'Starter Package',
                'page_url' => '/services/starter',
                'title' => 'Starter Package - $99 | Graveyard Jokes Studios',
                'meta_description' => 'Starter plan for new businesses: responsive web design, core development features, and a clean, launch-ready website at an affordable monthly cost.',
                'canonical_url' => $base . '/services/starter',
                'robots' => 'index,follow',
                'og_title' => 'Starter Package - $99 | Graveyard Jokes Studios',
                'og_description' => 'Starter plan for new businesses: responsive web design, core development features, and a clean, launch-ready website at an affordable monthly cost.',
                'og_image' => $cdn . '/images/aboutBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Starter Package - $99 | Graveyard Jokes Studios',
                'twitter_description' => 'Starter plan for new businesses: responsive web design, core development features, and a clean, launch-ready website at an affordable monthly cost.',
                'twitter_image' => $cdn . '/images/aboutBanner.webp',
                'schema_json' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Service',
                    'serviceType' => 'Web Design',
                    'name' => 'Starter Package',
                    'description' => 'Perfect for entrepreneurs and creatives launching their online presence. Single-page responsive website with contact form and social media integration.',
                    'provider' => [
                        '@type' => 'Organization',
                        'name' => 'GraveYard Jokes Studios Inc.',
                        'url' => $base,
                    ],
                    'offers' => [
                        '@type' => 'Offer',
                        'price' => '99',
                        'priceCurrency' => 'USD',
                        'availability' => 'https://schema.org/InStock',
                    ],
                    'areaServed' => 'US',
                ],
                'sitemap_priority' => 0.80,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'services.professional',
                'page_label' => 'Professional Package',
                'page_url' => '/services/professional',
                'title' => 'Professional Website Package - $149 | GraveYard Jokes Studios',
                'meta_description' => 'Professional plan for growing brands: custom multi-page design, advanced integrations, and performance optimization.',
                'canonical_url' => $base . '/services/professional',
                'robots' => 'index,follow',
                'og_title' => 'Professional Website Package - $149 | GraveYard Jokes Studios',
                'og_description' => 'Professional plan for growing brands: custom multi-page design, advanced integrations, and performance optimization.',
                'og_image' => $cdn . '/images/aboutBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Professional Website Package - $149 | GraveYard Jokes Studios',
                'twitter_description' => 'Professional plan for growing brands: custom multi-page design, advanced integrations, and performance optimization.',
                'twitter_image' => $cdn . '/images/aboutBanner.webp',
                'schema_json' => null,
                'sitemap_priority' => 0.80,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'services.premium',
                'page_label' => 'Premium Package',
                'page_url' => '/services/premium',
                'title' => 'Premium Package - $299 | Graveyard Jokes Studios',
                'meta_description' => 'Premium plan for established teams: full-service web design and development, priority support, advanced integrations, and ongoing strategic guidance.',
                'canonical_url' => $base . '/services/premium',
                'robots' => 'index,follow',
                'og_title' => 'Premium Package - $299 | Graveyard Jokes Studios',
                'og_description' => 'Premium plan for established teams: full-service web design and development, priority support, advanced integrations, and ongoing strategic guidance.',
                'og_image' => $cdn . '/images/aboutBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Premium Package - $299 | Graveyard Jokes Studios',
                'twitter_description' => 'Premium plan for established teams: full-service web design and development, priority support, advanced integrations, and ongoing strategic guidance.',
                'twitter_image' => $cdn . '/images/aboutBanner.webp',
                'schema_json' => null,
                'sitemap_priority' => 0.80,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'services.modernization-starter',
                'page_label' => 'Social Media - Starter',
                'page_url' => '/services/modernization-starter',
                'title' => 'Social Media Management - Starter - $99/mo | Graveyard Jokes Studios',
                'meta_description' => 'Starter social media management: consistent posting across 3 platforms every month. Content calendar, captions, hashtags, and monthly reporting.',
                'canonical_url' => $base . '/services/modernization-starter',
                'robots' => 'index,follow',
                'og_title' => 'Social Media Management - Starter - $99/mo | Graveyard Jokes Studios',
                'og_description' => 'Starter social media management: consistent posting across 3 platforms every month.',
                'og_image' => $cdn . '/images/aboutBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Social Media Management - Starter - $99/mo | Graveyard Jokes Studios',
                'twitter_description' => 'Starter social media management: consistent posting across 3 platforms every month.',
                'twitter_image' => $cdn . '/images/aboutBanner.webp',
                'schema_json' => null,
                'sitemap_priority' => 0.70,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'services.modernization-professional',
                'page_label' => 'Social Media - Professional',
                'page_url' => '/services/modernization-professional',
                'title' => 'Social Media Management - Professional - $149/mo | Graveyard Jokes Studios',
                'meta_description' => 'Professional social media management: full management across 5 platforms with stories, reels, community engagement, and bi-weekly reporting.',
                'canonical_url' => $base . '/services/modernization-professional',
                'robots' => 'index,follow',
                'og_title' => 'Social Media Management - Professional - $149/mo | Graveyard Jokes Studios',
                'og_description' => 'Full management across 5 platforms with stories, reels, community engagement, and bi-weekly reporting.',
                'og_image' => $cdn . '/images/aboutBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Social Media Management - Professional - $149/mo | Graveyard Jokes Studios',
                'twitter_description' => 'Full management across 5 platforms with stories, reels, and community engagement.',
                'twitter_image' => $cdn . '/images/aboutBanner.webp',
                'schema_json' => null,
                'sitemap_priority' => 0.70,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'services.modernization-premium',
                'page_label' => 'Social Media - Premium',
                'page_url' => '/services/modernization-premium',
                'title' => 'Social Media Management - Premium - $199/mo | Graveyard Jokes Studios',
                'meta_description' => 'Premium social media management: complete strategy with unlimited posts, ad campaigns, influencer outreach, and weekly strategy calls.',
                'canonical_url' => $base . '/services/modernization-premium',
                'robots' => 'index,follow',
                'og_title' => 'Social Media Management - Premium - $199/mo | Graveyard Jokes Studios',
                'og_description' => 'Complete social media strategy with unlimited posts, ad campaigns, influencer outreach, and weekly calls.',
                'og_image' => $cdn . '/images/aboutBanner.webp',
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Social Media Management - Premium - $199/mo | Graveyard Jokes Studios',
                'twitter_description' => 'Complete social media strategy with unlimited posts, ad campaigns, and influencer outreach.',
                'twitter_image' => $cdn . '/images/aboutBanner.webp',
                'schema_json' => null,
                'sitemap_priority' => 0.70,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'services.intake',
                'page_label' => 'Project Intake Form',
                'page_url' => '/services/intake',
                'title' => 'Project Intake Form | Graveyard Jokes Studios',
                'meta_description' => 'Tell us about your project and get started with a custom website from Graveyard Jokes Studios.',
                'canonical_url' => $base . '/services/intake',
                'robots' => 'noindex,nofollow',
                'og_title' => null,
                'og_description' => null,
                'og_image' => null,
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => null,
                'twitter_description' => null,
                'twitter_image' => null,
                'schema_json' => null,
                'sitemap_priority' => 0.50,
                'sitemap_change_freq' => 'monthly',
            ],
            [
                'page_key' => 'linkedin',
                'page_label' => 'LinkedIn',
                'page_url' => '/linkedin',
                'title' => 'LinkedIn | Graveyard Jokes Studios',
                'meta_description' => 'Connect with Graveyard Jokes Studios on LinkedIn — a creative web development studio building custom platforms for entrepreneurs, creatives, and independent brands.',
                'canonical_url' => $base . '/linkedin',
                'robots' => 'noindex,nofollow',
                'og_title' => 'LinkedIn | Graveyard Jokes Studios',
                'og_description' => 'Connect with Graveyard Jokes Studios on LinkedIn.',
                'og_image' => null,
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'LinkedIn | Graveyard Jokes Studios',
                'twitter_description' => 'Connect with Graveyard Jokes Studios on LinkedIn.',
                'twitter_image' => null,
                'schema_json' => null,
                'sitemap_priority' => 0.30,
                'sitemap_change_freq' => 'yearly',
            ],
            [
                'page_key' => 'legal.terms',
                'page_label' => 'Terms of Service',
                'page_url' => '/terms',
                'title' => 'Terms of Service | Graveyard Jokes Studios',
                'meta_description' => 'Read the Terms of Service for Graveyard Jokes Studios.',
                'canonical_url' => $base . '/terms',
                'robots' => 'noindex,follow',
                'og_title' => null,
                'og_description' => null,
                'og_image' => null,
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => null,
                'twitter_description' => null,
                'twitter_image' => null,
                'schema_json' => null,
                'sitemap_priority' => 0.30,
                'sitemap_change_freq' => 'yearly',
            ],
            [
                'page_key' => 'legal.privacy',
                'page_label' => 'Privacy Policy',
                'page_url' => '/privacy',
                'title' => 'Privacy Policy | Graveyard Jokes Studios',
                'meta_description' => 'Read the Privacy Policy for Graveyard Jokes Studios.',
                'canonical_url' => $base . '/privacy',
                'robots' => 'noindex,follow',
                'og_title' => null,
                'og_description' => null,
                'og_image' => null,
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => null,
                'twitter_description' => null,
                'twitter_image' => null,
                'schema_json' => null,
                'sitemap_priority' => 0.30,
                'sitemap_change_freq' => 'yearly',
            ],
            [
                'page_key' => 'legal.cookies',
                'page_label' => 'Cookie Policy',
                'page_url' => '/cookies',
                'title' => 'Cookie Policy | Graveyard Jokes Studios',
                'meta_description' => 'Read the Cookie Policy for Graveyard Jokes Studios.',
                'canonical_url' => $base . '/cookies',
                'robots' => 'noindex,follow',
                'og_title' => null,
                'og_description' => null,
                'og_image' => null,
                'og_type' => 'website',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => null,
                'twitter_description' => null,
                'twitter_image' => null,
                'schema_json' => null,
                'sitemap_priority' => 0.30,
                'sitemap_change_freq' => 'yearly',
            ],
        ];

        foreach ($pages as $page) {
            PageSeo::updateOrCreate(
                ['page_key' => $page['page_key']],
                $page
            );
        }
    }
}
